# Generated by Django 5.0.1 on 2024-02-21 07:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jadidlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hikmatli_sozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Hikmatli soz')),
                ('text_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Hikmatli soz')),
                ('text_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Hikmatli soz')),
                ('text_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Hikmatli soz')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('jadid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hikmatli_sozlar', to='jadidlar.jadid')),
            ],
            options={
                'verbose_name': 'Hikmatli soz',
                'verbose_name_plural': 'Hikmatli sozlar',
            },
        ),
    ]
