# Generated by Django 5.0.1 on 2024-02-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanlovlar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanlovlar',
            name='qiymat',
        ),
        migrations.RemoveField(
            model_name='tanlovlar',
            name='type',
        ),
        migrations.AddField(
            model_name='tanlovlar',
            name='Email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='tanlovlar',
            name='Facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='tanlovlar',
            name='Instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='tanlovlar',
            name='Telefon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='tanlovlar',
            name='Telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram'),
        ),
    ]
