# Generated by Django 5.0.1 on 2024-02-21 07:32

import django.db.models.deletion
import manbalar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('title_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('audio', models.FileField(upload_to='audios/', validators=[manbalar.models.validate_audio_extension])),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audiolar',
            },
        ),
        migrations.CreateModel(
            name='Rasmlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('title_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('image', models.ImageField(upload_to='images/', validators=[manbalar.models.validate_image_extension])),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
            },
        ),
        migrations.CreateModel(
            name='Videolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('title_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', validators=[manbalar.models.validate_video_extension])),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('file', models.FileField(upload_to='files/')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audios/', validators=[manbalar.models.validate_audio_extension])),
                ('audiolarmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='manbalar.audiolar')),
            ],
        ),
        migrations.CreateModel(
            name='RasmlarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('rasimlarmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasimlar', to='manbalar.rasmlar')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/', validators=[manbalar.models.validate_video_extension])),
                ('videolarmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='manbalar.videolar')),
            ],
        ),
    ]
