# Generated by Django 5.0.1 on 2024-02-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manbalar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolar',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='audiolar',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='audiolar',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='audiolar',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='rasmlar',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='rasmlar',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='rasmlar',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='rasmlar',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='videolar',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='videolar',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='videolar',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='videolar',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
    ]
