# Generated by Django 5.0.1 on 2024-03-06 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manbalar', '0002_alter_audiolar_title_alter_audiolar_title_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolar',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_audiolar', to=settings.AUTH_USER_MODEL),
        ),
    ]
