# Generated by Django 5.0.1 on 2024-03-10 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manbalar', '0004_rasmlar_blog_views_rasmlar_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolar',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='liked_audiolar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='liked_rasmlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='audiolar',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='rasmlar',
            name='likes',
        ),
        migrations.AddField(
            model_name='audiolar',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
