# Generated by Django 5.0.1 on 2024-02-21 07:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanferensiyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi')),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kanferensiya',
                'verbose_name_plural': 'Kanferensiyalar',
            },
        ),
        migrations.CreateModel(
            name='Seminarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi')),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seminar',
                'verbose_name_plural': 'Seminarlar',
            },
        ),
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi')),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='KanferensiyalarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('kanferensiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanferensiya_images', to='tadbirlar.kanferensiyalar')),
            ],
        ),
        migrations.CreateModel(
            name='SeminarlarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_images', to='tadbirlar.seminarlar')),
            ],
        ),
        migrations.CreateModel(
            name='YangiliklarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('yangilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yangilik_images', to='tadbirlar.yangiliklar')),
            ],
        ),
    ]
