# Generated by Django 5.0.1 on 2024-02-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tadbirlar', '0002_yangiliklar_blog_views_yangiliklar_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yangiliklar',
            name='blog_views',
        ),
        migrations.RemoveField(
            model_name='yangiliklar',
            name='likes',
        ),
    ]
