# Generated by Django 5.0.1 on 2024-03-05 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadbirlar', '0004_yangiliklar_blog_views_yangiliklar_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangiliklar',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_yangiliklar', to=settings.AUTH_USER_MODEL),
        ),
    ]
