# Generated by Django 5.0.1 on 2024-03-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadbirlar', '0005_alter_yangiliklar_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangiliklar',
            name='blog_views',
            field=models.IntegerField(default=0),
        ),
    ]
