# Generated by Django 5.0.1 on 2024-04-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadbirlar', '0008_kanferensiyalar_users_seminarlar_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanferensiyalar',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='kanferensiyalar',
            name='title_en',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='kanferensiyalar',
            name='title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='kanferensiyalar',
            name='title_uz',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='seminarlar',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='seminarlar',
            name='title_en',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='seminarlar',
            name='title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='seminarlar',
            name='title_uz',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='yangiliklar',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='yangiliklar',
            name='title_en',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='yangiliklar',
            name='title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='yangiliklar',
            name='title_uz',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
    ]
