# Generated by Django 5.0.1 on 2024-04-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadbirlar', '0009_alter_kanferensiyalar_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangiliklar',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
