# Generated by Django 5.0.1 on 2024-04-15 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jadidlar', '0006_alter_jadid_blog_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arxiv_hujjatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('type', models.CharField(blank=True, choices=[('ARXIV', 'ARXIV'), ('SKANER', 'SKANER')], default='ARXIV', max_length=6, null=True, verbose_name='turi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(upload_to='files/arxiv_hujjatlar', verbose_name='fayl')),
                ('count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('users', models.ManyToManyField(blank=True, related_name='liked_arxiv_hujjatlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arxiv hujjat',
                'verbose_name_plural': 'Arxiv hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='Arxiv_hujjatlarFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/arxiv_hujjatlar')),
                ('arxiv_hujjatlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hujjatlar.arxiv_hujjatlar')),
            ],
        ),
        migrations.CreateModel(
            name='Asarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('turkiston_muxtoriyati', models.BooleanField(default=False, verbose_name='Turkiston muxtoriyati')),
                ('tadqiqotlar', models.BooleanField(default=False, verbose_name='Tadqiqotlar')),
                ('til_va_imlo', models.BooleanField(default=False, verbose_name='Til va imlo')),
                ('likes', models.IntegerField(default=0)),
                ('jadid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asarlar', to='jadidlar.jadid')),
                ('users', models.ManyToManyField(blank=True, related_name='liked_asarlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asar',
                'verbose_name_plural': 'Asarlar',
            },
        ),
        migrations.CreateModel(
            name='AsarlarFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/asarlar')),
                ('asarlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hujjatlar.asarlar')),
            ],
        ),
        migrations.CreateModel(
            name='Dissertatsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/dissertatsiya', verbose_name='fayl')),
                ('count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='o`zgartirilgan sana')),
                ('likes', models.IntegerField(default=0)),
                ('users', models.ManyToManyField(blank=True, related_name='liked_dissertatsiya', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dissertatsiya',
                'verbose_name_plural': 'Dissertatsiyalar',
            },
        ),
        migrations.CreateModel(
            name='DissertatsiyaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/dissertatsiya')),
                ('dissertatsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hujjatlar.dissertatsiya')),
            ],
        ),
        migrations.CreateModel(
            name='Hotiralar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(upload_to='files/hotiralar', verbose_name='fayl')),
                ('count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='o`zgartirilgan sana')),
                ('type', models.CharField(blank=True, choices=[('Turkiston muxtoriyati', 'Turkiston muxtoriyati'), ('Tadqiqotlar', 'Tadqiqotlar'), ('Til va imlo', 'Til va imlo')], default='Turkiston muxtoriyati', max_length=25, null=True, verbose_name='turi')),
                ('likes', models.IntegerField(default=0)),
                ('jadid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotiralar', to='jadidlar.jadid')),
                ('users', models.ManyToManyField(blank=True, related_name='liked_hotiralar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotira',
                'verbose_name_plural': 'Hotiralar',
            },
        ),
        migrations.CreateModel(
            name='HotiralarFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/hotiralar')),
                ('count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('hotiralar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hujjatlar.hotiralar')),
            ],
        ),
        migrations.CreateModel(
            name='Maqolalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(upload_to='files/maqolalar', verbose_name='fayl')),
                ('count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='o`zgartirilgan sana')),
                ('turkiston_muxtoriyati', models.BooleanField(blank=True, default=False, null=True, verbose_name='Turkiston muxtoriyati')),
                ('tadqiqotlar', models.BooleanField(default=False, verbose_name='Tadqiqotlar')),
                ('til_va_imlo', models.BooleanField(default=False, verbose_name='Til va imlo')),
                ('type', models.CharField(blank=True, choices=[('Tarix', 'Tarix'), ('Siyosat', 'Siyosat'), ('Iqtisod', 'Iqtisod'), ('Madaniyat va sanat', 'Madaniyat va sanat'), ('Ijtimoiy masalalar va din', 'Ijtimoiy masalalar va din'), ('Adabiyot', 'Adabiyot'), ('Talim - Tarbiya', 'Talim - Tarbiya'), ('Boshqa masalalar', 'Boshqa masalalar'), ('Bibliografik korsatkich', 'Bibliografik korsatkich')], max_length=30, null=True, verbose_name='matbuotlar')),
                ('likes', models.IntegerField(default=0)),
                ('jadid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maqolalar', to='jadidlar.jadid')),
                ('users', models.ManyToManyField(blank=True, related_name='liked_maqolalar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
        migrations.CreateModel(
            name='MaqolalarFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/maqolalar')),
                ('maqolalar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hujjatlar.maqolalar')),
            ],
        ),
        migrations.CreateModel(
            name='Sherlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(upload_to='files/sherlar')),
                ('count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, choices=[('Turkiston muxtoriyati', 'Turkiston muxtoriyati'), ('Tadqiqotlar', 'Tadqiqotlar'), ('Til va imlo', 'Til va imlo')], default='Turkiston muxtoriyati', max_length=25, null=True, verbose_name='turi')),
                ('likes', models.IntegerField(default=0)),
                ('jadid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sherlar', to='jadidlar.jadid')),
                ('users', models.ManyToManyField(blank=True, related_name='liked_sherlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sher',
                'verbose_name_plural': 'Sherlar',
            },
        ),
        migrations.CreateModel(
            name='SherlarFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/sherlar')),
                ('sherlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hujjatlar.sherlar')),
            ],
        ),
        migrations.CreateModel(
            name='Tadqiqotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(upload_to='files/tadqiqotlar')),
                ('count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, choices=[('Turkiston muxtoriyati', 'Turkiston muxtoriyati'), ('Tadqiqotlar', 'Tadqiqotlar'), ('Til va imlo', 'Til va imlo')], default='Turkiston muxtoriyati', max_length=25, null=True, verbose_name='turi')),
                ('jadid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tadqiqotlar', to='jadidlar.jadid')),
            ],
            options={
                'verbose_name': 'Tadqiqot',
                'verbose_name_plural': 'Tadqiqotlar',
            },
        ),
        migrations.CreateModel(
            name='TadqiqotlarFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/tadqiqotlar')),
                ('tadqiqotlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hujjatlar.tadqiqotlar')),
            ],
        ),
    ]
