# Generated by Django 5.0.1 on 2024-04-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatlar', '0002_alter_maqolalar_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqolalar',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='maqolalar',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/maqolalar', verbose_name='fayl'),
        ),
        migrations.AlterField(
            model_name='maqolalar',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='o`zgartirilgan sana'),
        ),
    ]
