# Generated by Django 5.0.1 on 2024-04-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatlar', '0004_alter_maqolalar_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotiralar',
            name='type',
            field=models.CharField(blank=True, choices=[('Turkiston_muxtoriyati', 'Turkiston_muxtoriyati'), ('Tadqiqotlar', 'Tadqiqotlar')], default='Turkiston_muxtoriyati', max_length=25, null=True, verbose_name='turi'),
        ),
    ]
