# Generated by Django 5.0.1 on 2024-04-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatlar', '0005_alter_hotiralar_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sherlar',
            name='type',
            field=models.CharField(blank=True, choices=[('Turkiston_muxtoriyati', 'Turkiston muxtoriyati')], default='Turkiston_muxtoriyati', max_length=25, null=True, verbose_name='turi'),
        ),
    ]
