# Generated by Django 5.0.1 on 2024-04-19 05:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatlar', '0008_alter_tadqiqotlar_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arxiv_hujjatlar',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='arxiv_hujjatlar',
            name='title_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='arxiv_hujjatlar',
            name='title_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='arxiv_hujjatlar',
            name='title_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='nomi'),
        ),
    ]
