# Generated by Django 5.0.1 on 2024-04-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatlar', '0009_alter_arxiv_hujjatlar_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arxiv_hujjatlar',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='arxiv_hujjatlar',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='arxiv_hujjatlar',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='arxiv_hujjatlar',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nomi'),
        ),
    ]
