# Generated by Django 5.0.1 on 2024-04-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatlar', '0017_alter_maqolalar_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asarlar',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='asarlar',
            name='title_en',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='asarlar',
            name='title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='asarlar',
            name='title_uz',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='maqolalar',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='maqolalar',
            name='title_en',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='maqolalar',
            name='title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='maqolalar',
            name='title_uz',
            field=models.TextField(blank=True, null=True, verbose_name='nomi'),
        ),
    ]
