# Generated by Django 5.0.1 on 2024-02-21 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foydali_havolalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('title_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='nomi')),
                ('link', models.URLField(verbose_name='link')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logo_images/')),
            ],
            options={
                'verbose_name': 'Foydali_havola',
                'verbose_name_plural': 'Foydali_havolalar',
            },
        ),
        migrations.CreateModel(
            name='Foydali_havolalarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foydali_havola_images/')),
                ('foydali_havola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foydali_havola_images', to='foydali_havolalar.foydali_havolalar')),
            ],
        ),
    ]
