# Generated by Django 5.0.1 on 2024-02-21 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slayder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Tavsiv')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Tavsiv')),
                ('text_uz', models.TextField(blank=True, null=True, verbose_name='Tavsiv')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Tavsiv')),
                ('citations', models.CharField(max_length=255, verbose_name='Havolalar')),
                ('image', models.ImageField(upload_to='slayder')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slayder',
                'verbose_name_plural': 'Slayderlar',
            },
        ),
        migrations.CreateModel(
            name='SlayderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slayder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slayder_images', to='slayder.slayder')),
            ],
        ),
    ]
