# Generated by Django 5.0.1 on 2024-02-21 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ishtirokchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('fullname_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('fullname_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('fullname_en', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozimi')),
                ('position_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozimi')),
                ('position_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozimi')),
                ('position_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozimi')),
                ('image', models.ImageField(upload_to='image')),
            ],
            options={
                'verbose_name': 'Ishtirokchi',
                'verbose_name_plural': 'Ishtirokchilar',
            },
        ),
        migrations.CreateModel(
            name='IshtirokchilarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('ishtirokchilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ishtirokchi_images', to='ishtirokchilar.ishtirokchilar')),
            ],
        ),
    ]
