# Generated by Django 5.0.1 on 2024-03-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishtirokchilar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishtirokchilar',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
