# Generated by Django 5.0.1 on 2024-03-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishtirokchilar', '0002_ishtirokchilar_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishtirokchilar',
            name='order',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
