# Generated by Django 5.0.1 on 2024-04-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishtirokchilar', '0004_alter_ishtirokchilar_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishtirokchilar',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ishtirokchilar',
            name='fullname_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ishtirokchilar',
            name='fullname_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ishtirokchilar',
            name='fullname_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
