# Generated by Django 5.1.7 on 2025-03-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishtirokchilar', '0005_alter_ishtirokchilar_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishtirokchilar',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozimi'),
        ),
    ]
