# Generated by Django 5.1.7 on 2025-03-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishtirokchilar', '0006_ishtirokchilar_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishtirokchilar',
            name='degree_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Darajasi'),
        ),
        migrations.AddField(
            model_name='ishtirokchilar',
            name='degree_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Darajasi'),
        ),
        migrations.AddField(
            model_name='ishtirokchilar',
            name='degree_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Darajasi'),
        ),
        migrations.AlterField(
            model_name='ishtirokchilar',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Darajasi'),
        ),
    ]
