# Generated by Django 5.0.1 on 2024-02-21 07:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sahifalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sahifa nomi')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sahifa nomi')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sahifa nomi')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sahifa nomi')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Matn')),
                ('text_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Matn')),
                ('text_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Matn')),
                ('text_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(upload_to='files/', verbose_name='Fayl')),
                ('count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Sahifa',
                'verbose_name_plural': 'Sahifalar',
            },
        ),
        migrations.CreateModel(
            name='SahifalarFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/sahifalar')),
                ('sahifalar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sahifalar.sahifalar')),
            ],
        ),
    ]
