# Generated by Django 5.0.1 on 2024-02-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahifalar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahifalar',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Fayl'),
        ),
    ]
