# Generated by Django 5.0.1 on 2024-03-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadidlar', '0004_jadid_blog_views_jadid_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadid',
            name='likes',
        ),
        migrations.AlterField(
            model_name='jadid',
            name='blog_views',
            field=models.IntegerField(default=1000),
        ),
    ]
